version: "3.8"

services:
  db:
    image: mariadb:11.3
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=log_db
      - MARIADB_USER=app_user
      - MARIADB_PASSWORD=app_password
    ports:
      - "3306:3306" # opsional, agar bisa akses DB dari host
    volumes:
      - ./storage/db:/var/lib/mysql
      - ./storage/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MARIADB_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - appnet

  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    container_name: express-logs
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - DB_DATABASE=log_db
    ports:
      - "3000:3000"
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet: